<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Unassigned_Ei3xDxyc</name>
   <tag></tag>
   <elementGuidId>d7e3668f-06dd-4265-aa37-22c86127158c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Ei3xDxyc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='Ei3xDxyc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>e065d9fb-03b5-489e-92ed-d77f9b6fc11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Ei3xDxyc</value>
      <webElementGuid>df5a3e94-2909-4d69-974b-39d860608bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>427</value>
      <webElementGuid>3836a295-19a3-4ae4-b005-efa9e5f7aad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>397</value>
      <webElementGuid>4907504a-02ef-4c7b-b715-3e9fcdd94c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Ei3xDxyc&quot;)</value>
      <webElementGuid>6033dea5-2563-43c2-b89a-0ffee5157666</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='Ei3xDxyc']</value>
      <webElementGuid>f3ca078e-6457-4df6-8a4b-3cd9b152fb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[7]/div/div[2]/div/div/canvas</value>
      <webElementGuid>8ce78680-e38c-449d-8342-0c745fc58908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/canvas</value>
      <webElementGuid>daca970d-91d1-4dcb-9baa-3b352662aff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'Ei3xDxyc']</value>
      <webElementGuid>b39f54ae-aa2d-467a-b4e9-f191d0a5c888</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
