<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Today_oQWSbULU</name>
   <tag></tag>
   <elementGuidId>474ab7bf-415d-4d4d-97e6-631b0cc7d679</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oQWSbULU</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='oQWSbULU']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>26331ca9-16b1-430e-b7aa-497724b60fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oQWSbULU</value>
      <webElementGuid>5bfa9279-a457-44ea-b546-1db361db645c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>427</value>
      <webElementGuid>8d844b68-eb31-4654-8a95-d9119540b238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>397</value>
      <webElementGuid>39890ab2-1814-4459-8ada-acfe1966c6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oQWSbULU&quot;)</value>
      <webElementGuid>9e001306-3444-4c2e-a7a0-63bc861af216</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='oQWSbULU']</value>
      <webElementGuid>a092fbfb-2f09-49b3-9c73-fd4abcb28c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[6]/div/div[2]/div/div/canvas</value>
      <webElementGuid>392132e0-0813-4357-bab5-ecb81d986807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/canvas</value>
      <webElementGuid>e2d8d746-0805-4ab1-a7ae-d3f562101620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'oQWSbULU']</value>
      <webElementGuid>db159f86-bfa3-480c-90c5-07d35e77abf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
