<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vfb-3</name>
   <tag></tag>
   <elementGuidId>ef6fe58a-e946-45cc-94c6-baa7126a91e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69247d8c-a47f-43c8-8b7e-041df1ccf21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae009f72-b4d9-46dd-8d5f-1928e6c8c7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-3</value>
      <webElementGuid>5eb45cdd-963f-47c1-8568-a06de7f7122a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-3</value>
      <webElementGuid>1da2d80e-7713-4190-9a75-df9e82fb5323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text vfb-medium required {digits:true,maxlength:2,minlength:2} vfb-error</value>
      <webElementGuid>3f71ef2d-874d-4a6e-8736-b444e3dabe08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-3&quot;)</value>
      <webElementGuid>744619a3-6db2-447f-932a-749f9ad99a07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-3']</value>
      <webElementGuid>948f2bbc-66ba-4171-a552-316de50f3999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='item-vfb-2']/ul/li/span/input</value>
      <webElementGuid>32abec0d-eed2-48c6-900b-8125c66298ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/ul/li/span/input</value>
      <webElementGuid>96a057f6-38ee-4f4b-ab5b-e772525bfd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-3' and @id = 'vfb-3']</value>
      <webElementGuid>c718bc90-3a30-4303-8fa4-0452e03bd4c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
