<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Jasmine  Morgan2020-10-08 0851 AMHappy _b117b4</name>
   <tag></tag>
   <elementGuidId>b9abca7d-2ea0-4265-b2df-77a532f3e141</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.oxd-sheet.oxd-sheet--rounded.oxd-sheet--white.orangehrm-buzz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f7a4e62-6821-4d6b-b799-d7f93a810737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-sheet oxd-sheet--rounded oxd-sheet--white orangehrm-buzz</value>
      <webElementGuid>79a2be2a-fa5a-463f-bfce-67539f90f797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jasmine  Morgan2020-10-08 08:51 AMHappy Birthday to my darling little son!!! Thanks guys for your presence at the party. Read More5 Likes3 Comments ‚  0 Shares</value>
      <webElementGuid>b5ecba50-8dc7-4b2e-944f-d8568a62f88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;oxd-grid-2 orangehrm-buzz-layout&quot;]/div[@class=&quot;oxd-grid-item oxd-grid-item--gutters&quot;]/div[@class=&quot;orangehrm-buzz-newsfeed&quot;]/div[@class=&quot;oxd-grid-1 orangehrm-buzz-newsfeed-posts&quot;]/div[@class=&quot;oxd-grid-item oxd-grid-item--gutters&quot;]/div[@class=&quot;oxd-sheet oxd-sheet--rounded oxd-sheet--white orangehrm-buzz&quot;]</value>
      <webElementGuid>d11996d1-5d1f-44c1-8560-05fc1e4a91bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div[3]/div/div</value>
      <webElementGuid>d61ef65b-6f13-45b0-aef6-4e3476450982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>e6ab4b7e-9058-4c8a-b481-391386b35e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Jasmine  Morgan2020-10-08 08:51 AMHappy Birthday to my darling little son!!! Thanks guys for your presence at the party. Read More5 Likes3 Comments ‚  0 Shares' or . = 'Jasmine  Morgan2020-10-08 08:51 AMHappy Birthday to my darling little son!!! Thanks guys for your presence at the party. Read More5 Likes3 Comments ‚  0 Shares')]</value>
      <webElementGuid>9fb59943-f651-42ff-887d-397947f21d75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
