<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_DirectoryMaintenanceClaim</name>
   <tag></tag>
   <elementGuidId>4cca41d0-45ef-40bb-bfb6-f87867ae0def</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/aside/nav/div[2]/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.oxd-main-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>b58d8623-664b-4df0-9dde-8f4d0ea11e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-main-menu</value>
      <webElementGuid>71c25ace-a2f1-4fbe-bd86-065be0dde436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>管理员个人信息管理系统休假时间招聘我的信息绩效仪表盘DirectoryMaintenanceClaim激动</value>
      <webElementGuid>713656bc-5168-4090-846f-9fa5c7fc771b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-navigation&quot;]/aside[@class=&quot;oxd-sidepanel&quot;]/nav[@class=&quot;oxd-navbar-nav&quot;]/div[@class=&quot;oxd-sidepanel-body&quot;]/ul[@class=&quot;oxd-main-menu&quot;]</value>
      <webElementGuid>cc9c8a95-4f26-4c26-a19c-03e5b564baa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/aside/nav/div[2]/ul</value>
      <webElementGuid>5c6cd957-c6f6-4ef6-9a5b-a091449005f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>8eb92419-1b7a-45de-b104-cd0bbda2620e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = '管理员个人信息管理系统休假时间招聘我的信息绩效仪表盘DirectoryMaintenanceClaim激动' or . = '管理员个人信息管理系统休假时间招聘我的信息绩效仪表盘DirectoryMaintenanceClaim激动')]</value>
      <webElementGuid>639ae04b-5ce3-463f-90bb-34296aed8f9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
